/* eslint-disable import/prefer-default-export */
export const vehicleData = [
  {
    title: 'Engine Type*',
    options: [
      { name: 'Petrol', value: '1' },
      { name: 'Diesel', value: '2' },
      { name: 'LPG', value: '3' },
      { name: 'CNG', value: '4' },
      { name: 'Hybrid', value: '5' },
      { name: 'Electric', value: '6' },
    ],
  },
  {
    title: 'Assembly*',
    options: [
      { name: 'Local', value: '1' },
      { name: 'Imported', value: '2' },
    ],
  },
  {
    title: 'Transmission*',
    options: [
      { name: 'Manual', value: '1' },
      { name: 'Automatic', value: '2' },
    ],
  },
  {
    title: 'Body Type*',
    options: ['Compact sedan', 'Compact SUV', 'Convertible', 'Coupe', 'Crossover', 'Hatchback', 'Sedan', 'SUV', 'Wagon', 'Other'],
  },
  {
    title: 'Installment*',
    options: [
      { name: 'Yes', value: '1' },
      { name: 'No', value: '2' },
    ],
  },
  {
    title: 'Installment Plan',
    options: [
      { name: 'Flexible', value: '1' },
      { name: '1 Year', value: '2' },
      { name: '3 Years', value: '3' },
      { name: 'Other', value: '4' },
    ],
  },
  {
    title: 'Features',
    options: [
      'ABS',
      'Air Conditioning',
      'Air Bag',
      'Anti Lock Brakes',
      'Anti Theft Device',
      'Auxiliary Heating',
      'Backup Camera',
      'Brake Assist',
      'Brake Warning',
      'Child Safety Lock',
      'Cruise Control',
      'CD Player',
      'Cool Box',
      'Climate Control',
      'DVD Player',
      'Dual Air Bags',
      'Electric Mirrors',
      'Electric Windows',
      'Fog Lights',
      'Heated Seats',
      'Keyless Entry',
      'Leather Seats',
      'Navigation System',
      'Power Steering',
      'Power Windows',
      'Rear Air Conditioning',
      'Rear Window Defroster',
      'Rear Window Wiper',
      'Remote Start',
      'Rear Defroster',
      'Rear Window Defroster',
      'Rear Camera',
      'Sun Roof',
      'Tinted Glass',
      'Tow Package',
      'Trip Computer',
      'USB Connectivity',
      'Vanity Mirrors',
      'Xenon Headlights',
      'Parking Sensors',
      'Wireless Charging',
    ],
  },
];
